<?php include('header.php') ?>


<div class="container no-pad-max-992">
	<h2 class="heading-primary">User agreement and privacy policy</h2>

	<div id="faq" class="clearfix">


	<section class="entry">
	    <p>PLEASE READ THIS TERMS OF USE AGREEMENT (THE <b>"TERMS OF USE"</b>) CAREFULLY. BY ACCESSING OR USING THIS WEBSITE OR ANY OTHER WEBSITES OF KIDSTIR, INC., ITS AFFILIATES OR AGENTS (<b>"KIDSTIR</b>" OR "<b>WE</b>") WITH LINKS TO THIS TERMS OF USE (COLLECTIVELY, THE <b>"WEBSITE"</b>) IN ANY WAY, INCLUDING USING THE SERVICES AND RESOURCES AVAILABLE OR ENABLED VIA THE WEBSITE (EACH A <b>"SERVICE"</b> AND COLLECTIVELY, THE <b>"SERVICES"</b>) BY KIDSTIR OR USERS OF THE SITE (<b>"USERS"</b>), CLICKING ON THE "I ACCEPT" BUTTON, COMPLETING THE REGISTRATION PROCESS, AND/OR MERELY BROWSING THE WEBSITE, YOU REPRESENT THAT (1) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THE TERMS OF USE, (2) YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH KIDSTIR, AND (3) YOU HAVE THE AUTHORITY TO ENTER INTO THE TERMS OF USE PERSONALLY OR ON BEHALF OF THE COMPANY YOU HAVE NAMED AS THE CUSTOMER, AND TO BIND THAT COMPANY TO THE TERMS OF USE. THE TERM <b>"YOU"</b> REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE CUSTOMER WHEN YOU REGISTERED ON THE WEBSITE. IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF USE, YOU MAY NOT ACCESS OR USE THIS WEBSITE OR THE SERVICES.</p>
<p><b>IF YOU SUBSCRIBE TO OUR SERVICES FOR A TERM (THE "INITIAL TERM") AND BECOME A KIDSTIR MEMBER, THEN THE TERMS WILL BE AUTOMATICALLY RENEWED FOR ADDITIONAL PERIODS OF THE SAME DURATION AS THE INITIAL TERM AT KIDSTIR'S THEN-CURRENT FEE FOR SUCH SERVICES UNLESS YOU TERMINATE YOUR MEMBERSHIP IN ACCORDANCE WITH SECTION 1.5, 10.2 AND 15.4 BELOW. HOWEVER, THE FOREGOING WILL NOT APPLY TO ANY GIFT SUBSCRIPTION.</b></p>
<p><b>THE TERMS OF USE REQUIRE THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE.</b></p>
<p>Your use of, and participation in, certain Services may be subject to additional terms (<b>"Supplemental Terms"</b>) and such Supplemental Terms will either be listed in the Terms of Use or will be presented to you for your acceptance when you sign up to use the supplemental Service. If the Terms of Use are inconsistent with the Supplemental Terms, the Supplemental Terms shall control with respect to such Service. The Terms of Use and any applicable Supplemental Terms are referred to herein as the <b>"Terms."</b></p>
<p>We know that your privacy is important. For this reason, we have created a privacy policy that describes our collection, use and disclosure practices regarding any personal information that you provide to us. The security of your personal information is important to us. While there is no such thing as &#8220;perfect security&#8221; on the Internet, we will take reasonable steps to help ensure the safety of your personal information. However, you understand and agree that such steps do not guarantee that the Website is invulnerable to all security breaches or immune from viruses, security threats or other vulnerabilities. We reserve the right to cooperate with local, state, provincial and national authorities in investigations of improper or unlawful activities and this may require the disclosure of your personal information.</p>
<p>PLEASE NOTE THAT The Terms are subject to change by Kidstir in its sole discretion at any time. When changes are made, Kidstir will make a new copy of the Terms of Use available at the Website and any new Supplemental Terms will be made available from within, or through, the affected Service on the Website. We will also update the "Last Updated" date at the top of the Terms of Use. If we make any material changes, and you have registered to use the Services, we will also send an e-mail to you at the last e-mail address you provided to us pursuant to the Terms. Any changes to the Terms will be effective immediately for new Users of the Website or Services and will be effective thirty (30) days after posting notice of such changes on the Website for existing Users, provided that any material changes shall be effective for Users who have a registered account on the Website upon the earlier of thirty (30) days after posting notice of such changes on the Website or thirty (30) days after dispatch of an e-mail notice of such changes to Registered Users (defined in Section 3.1 below). Kidstir may require you to provide consent to the updated Terms in a specified manner before further use of the Website or the Services is permitted. If you do not agree to any change(s) after receiving a notice of such change(s), you shall stop using the Website and/or the Services. Otherwise, your continued use of the Website and/or Services constitutes your acceptance of such change(s). PLEASE REGULARLY CHECK THE WEBSITE TO VIEW THE THEN-CURRENT TERMS.</p>
<p><b>1. </b><b>OUR OFFERING</b>. Our Services are for parents (and not for children) who want to spark a love of good food in their family. When you initially subscribe to our Services and become a "<b>Member</b>", we will send to you a Cookbook Kit, which includes a cookbook binder, recipes and/or tools. Then, each month as long as you maintain your subscription as a Member, you will receive a different "<b>Kit</b>" for your binder. Kits may include recipes, cooking tools and/or ingredients. We may also sell Kits and other products ("<b>Products</b>") on a stand-alone basis. SOME PRODUCTS MAY CONSITUTE CHOKING HAZARDS AND/OR CONTAIN SMALL PARTS OR OTHERWISE DANGEROUS COMPONENTS. PLEASE BE CAREFUL. KITS ARE NOT FOR CHILDREN UNDER THREE (3) YEARS OF AGE AND SHOULD NOT BE USED BY ANY CHILD WITHOUT ADULT SUPERVISION. YOU ACKNOWLEDGE THAT THE PRODUCTS ARE NOT DESIGNED, MANUFACTURED OR INTENDED FOR USE BY CHILDREN UNDER THE AGE OF THREE (3) AND MAY CONTAIN SMALL PARTS. IN ADDITION TO ALL OTHER LIMITATIONS AND DISCLAIMERS IN THIS AGREEMENT, KIDSTIR SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY, IN WHOLE OR IN PART, FOR ANY CLAIMS, LIABILITY, DAMAGES, LOSS OR COSTS ARISING FROM SUCH USE</p>
<p><b>1.1 </b><b><span class="underline-text">Kits</span></b>. Membership fees are set forth on our Website, as may be amended from time to time. If you are a Member, Kidstir will send you an email when your Kit has shipped each month. Kits will be shipped on or about the 1st day of every month to the address in your Account (defined below). Kidstir reserves the right to make deliveries in installments. Membership includes any applicable shipping, handling and taxes for the Kits, except in California and where otherwise required by law, where sales tax will be separately charged.. All Kits shall be deemed accepted by you upon shipment, and title to, and risk of loss of, each Kit passes to you when Kidstir provides the Kit(s) to a common carrier. All Kits are non-refundable and cannot be returned. However, please contact us if any or all of your Kit is damaged and we will work with you to provide a replacement Kit or component.</p>
<p><b>1.2 </b><b><span class="underline-text">Shipment</span></b>. Currently, we ship to the United States only. Any estimated shipping date provided by Kidstir is based on Product availability and payment processing time, and does not include transit time. All Products shall be deemed accepted by you upon shipment, and title to, and risk of loss of, the Products passes to you when Kidstir provides the Product(s) to a common carrier.  Kidstir reserves the right to charge an additional fee if you request that any Products be re-shipped, whether because you originally submitted an incorrect address when you placed your order with Kidstir or otherwise. Accordingly, please be sure and review the shipping information you submit very closely to ensure it is accurate.</p>
<p><b>1.3 </b><b><span class="underline-text">Standalone Orders</span></b><span class="underline-text">.</span> When you place an order for Products (other than Membership) (such order, an "<b>Order</b>"), that will constitute an offer to purchase the Product(s) ordered and we may accept your Order by processing your payment and shipping the Product(s). Your receipt of an electronic or other form of Order confirmation does not signify our acceptance of your Order, nor does it constitute confirmation of our offer to sell. For any reason, we may decline to accept your Order or any part of your Order. No Order will be considered accepted by Kidstir until the Product(s) has been shipped. If some of Products in your Order are temporarily out of stock, we will ship the available Products only and notify you of any Products that cannot be fulfilled. If we decline to accept your Order, we will attempt to notify you at the email address you provided. We further reserve the right any time after receipt of your Order, without prior notice to you, to supply less than the quantity you ordered of any item. Your Order will be deemed accepted by Kidstir upon our delivery of the Products that you have ordered. We may require additional verifications or information before accepting any Order. All Products shall be deemed accepted by you upon shipment, and title to, and risk of loss of, the Products pass to you when Kidstir provides the Product(s) to a common carrier. All sales of Products are subject to our then-current return policies, as posted on the Website. Any estimated shipping date provided by Kidstir is based on Product availability and payment processing time, and does not include transit time.</p>
<p><b>1.4 </b><b><span class="underline-text">Products</span></b>. We make efforts to display our Products and their colors as accurately as possible. Having said that, the displayed colors of the Products will depend upon your monitor and we cannot guarantee that your monitor will accurately portray the actual colors of the Products. Products displayed may be out-of-stock or discontinued, and prices are subject to change. We cannot confirm the price of an item until you place an Order. Despite our best efforts, a small number of the items on our Website may be mispriced. We are not responsible for typographical errors regarding price or any other matter. All prices do include shipping and handling and sales taxes (except in California and where otherwise required by law, where tax will be added to your total purchase price). You are responsible for the payment of any shipping and handling charges and state and local sales or use taxes that may apply to your order.</p>
<p><b>1.5 </b><b><span class="underline-text">Membership</span></b>. Except as set forth below, members can cancel their Membership at any time, and will only be billed for the current month's Kit.  There are no cancellation fees or penalties.  To cancel your Membership, simply log into your Account and select the designated option to submit your cancellation.  Your cancellation request must be received before 12 AM Eastern Standard Time <b><span class="underline-text">SEVEN ("7") DAYS PRIOR</span></b> to the next re-billing date, otherwise you will continue to be billed for the next planned kit. If you do cancel, you will not receive any additional deliveries from Kidstir after the current subscription period. If an error occurs, whereby you do receive a delivery after your cancellation submission which has not been paid for, regardless of where the error initiated, you agree to: (a) notify Kidstir of the error, at which time Kidstir will advise you how to return the contents of the Kit to Kidstir; or (b) keep the Kit and pay the then current cost of the Kit. "Multiple month" subscriptions (3, 6 months and any term yet to be made available) that are offered as gift subscriptions are billed upfront and are not eligible for cancellation during the initial subscription term. Such gift subscriptions will also not automatically renew.</p>
<p><b>1.6 </b><b><span class="underline-text">Refer a Friend</span></b>. As a Member, by referring your friends to Kidstir, you may participate in the Kidstir Refer A Friend Program (the "<b>Program</b>"), which is a loyalty program we offer to our Members. If you choose to participate in the Program, for each friend you refer to Kidstir for which a Qualifying Referral (defined below) is completed, you may be able to receive credits toward future purchases. In order to receive a Referral Reward, each of the following requirements must be met (collectively, a &#8220;<b>Qualifying Referral</b>&#8220;): (i) you must log in to your Account on the Site and select the &#8220;Refer My Friends&#8221; link; (ii) you must share the link provided with friends via Facebook and Twitter, by copying and pasting the unique referral link generated via the Services, or by sending the unique referral link generated via the Services in an email via the Services to your friends; (iii) a friend who clicks the link on Facebook, Twitter or otherwise or clicks the link contained in the email must create a Kidstir Account and complete a purchase of a Membership through the Site or Services. Gift Certificate purchases or purchases of stand-alone Products are not Qualifying Referrals. Satisfaction of a Qualifying Referral and the applicable referral credits ("<b>Rewards</b>") you receive will be reflected in your Account in a commercially reasonable amount of time after the Qualifying Referral has been completed. The Rewards you accrue will be displayed in your My Account profile page. Rewards can be accrued solely by you and you may not earn Rewards by permitting another individual to use your Account. Rewards accrued in multiple Accounts may not be combined into one Account. You may not earn Rewards by creating multiple Accounts. You may not post your unique referral link on any public forum or coupon site, doing so will result in the reversal of any Rewards earned and may result in your account becoming suspended. By acquiring Rewards, you agree and acknowledge that Kidstir is granting you a limited, revocable license to a digital item, and that Rewards are not your personal property. You may not obtain any cash or money in exchange for Rewards. Except as explicitly provided herein, Rewards are non-transferable. Members are responsible for keeping track of the Rewards in their Accounts.</p>
<p><b>2. </b><b>Use of the Services and Kidstir Properties.</b> The Application, the Software, the Website, the Services, and the information and content available on the Website and in the Services (as these terms are defined below) (collectively, the <b>"Kidstir Properties"</b>) are protected by copyright laws throughout the world. Subject to the Terms, Kidstir grants you a limited license to reproduce portions of the Kidstir Properties for the sole purpose of using the Services for your personal or internal business purposes. Unless otherwise specified by Kidstir in a separate license, your right to use any Kidstir Properties is subject to the Terms.</p>
<p><b>2.1 </b><b><span class="underline-text">Kidstir Software</span>. </b>Use of any software and associated documentation, other than the Application, that is made available via the Website or the Services (<b>"Software"</b>) is governed by the terms of the license agreement that accompanies or is included with the Software, or by the license agreement expressly stated on the Website page(s) accompanying the Software. These license terms may be posted with the Software downloads or at the Website page where the Software can be accessed. You shall not use, download or install any Software that is accompanied by or includes a license agreement unless you agree to the terms of such license agreement. At no time will Kidstir provide you with any tangible copy of our Software. Kidstir shall deliver access to the Software via electronic transfer or download and shall not use or deliver any tangible media in connection with the (a) delivery, installation, updating or problem resolution of any Software (including any new releases); or (b) delivery, correction or updating of documentation. For the purposes of this section tangible media shall include, but not be limited to, any tape disk, compact disk, card, flash drive, or any other comparable physical medium. Unless the accompanying license agreement expressly allows otherwise, any copying or redistribution of the Software is prohibited, including any copying or redistribution of the Software to any other server or location, or redistribution or use on a service bureau basis. If there is any conflict between the Terms and the license agreement, the license agreement shall take precedence in relation to that Software (except as provided in the following sentence). If the Software is a pre-release version, then, notwithstanding anything to the contrary included within an accompanying license agreement, you are not permitted to use or otherwise rely on the Software for any commercial or production purposes. If no license agreement accompanies use of the Software, use of the Software will be governed by the Terms. Subject to your compliance with the Terms, Kidstir grants you a non-assignable, non-transferable, non-sublicensable, revocable non-exclusive license to use the Software for the sole purpose of enabling you to use the Services in the manner permitted by the Terms. Some Software may be offered under an open source license that we will make available to you. There may be provisions in the open source license that expressly override some of these terms.</p>
<p><b>2.2 </b><b><span class="underline-text">Updates</span>.</b> You understand that the Kidstir Properties are evolving. As a result, Kidstir may require you to accept updates to the Kidstir Properties that you have installed on your computer or mobile device. You acknowledge and agree that Kidstir may update the Kidstir Properties with or without notifying you. You may need to update third-party software from time to time in order to use the Kidstir Properties.</p>
<p><b>2.3 </b><b><span class="underline-text">Certain Restrictions</span>.</b> The rights granted to you in the Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, reproduce, distribute, host or otherwise commercially exploit the Kidstir Properties or any portion of the Kidstir Properties, including the Website, (b) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other Kidstir Properties (including images, text, page layout or form) of Kidstir; (c) you shall not use any metatags or other "hidden text" using Kidstir's name or trademarks; (d) you shall not modify, translate, adapt, merge, make derivative works of, disassemble, decompile, reverse compile or reverse engineer any part of the Kidstir Properties except to the extent the foregoing restrictions are expressly prohibited by applicable law; (e) you shall not use any manual or automated software, devices or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools or the like) to "scrape" or download data from any web pages contained in the Website (except that we grant the operators of public search engines revocable permission to use spiders to copy materials from the Website for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials); (f) access the Kidstir Properties in order to build a similar or competitive website, application or service; (g) except as expressly stated herein, no part of the Kidstir Properties may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means; and (h) you shall not remove or destroy any copyright notices or other proprietary markings contained on or in the Kidstir Properties. Any future release, update or other addition to the Kidstir Properties shall be subject to the Terms. Kidstir, its suppliers and service providers reserve all rights not granted in the Terms. Any unauthorized use of the Kidstir Properties terminates the licenses granted by Kidstir pursuant to the Terms.</p>
<p><b>2.4 </b><b><span class="underline-text">Third-Party Materials</span>.</b> As a part of the Kidstir Properties, you may have access to materials that are hosted by another party. You agree that it is impossible for Kidstir to monitor such materials and that you access these materials at your own risk.</p>
<p><b>3. </b><b>Registration.</b></p>
<p><b>3.1 </b><b><span class="underline-text">Registering Your Account</span>.</b> In order to access certain features of the Kidstir Properties you may be required to become a Registered User. For purposes of the Terms, a <b>"Registered User"</b> is a User who has registered an account on the Website (<b>"Account"</b>).</p>
<p><b>3.2 </b><b><span class="underline-text">Access Through a SNS</span>.</b> We may enable you to link your Account with a valid account on a social networking service ("<b>SNS</b>" and each such account, a <b>"Third-Party Account"</b>) by allowing Kidstir to access your Third-Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third-Party Account. You represent that you are entitled to grant Kidstir access to your Third-Party Account (including, but not limited to, for use for the purposes described herein) without breach by you of any of the terms and conditions that govern your use of the applicable Third-Party Account and without obligating Kidstir to pay any fees or making Kidstir subject to any usage limitations imposed by such third-party service providers. By granting Kidstir access to any Third-Party Accounts, you understand that Kidstir may access, make available and store (if applicable) any information, data, text, software, music, sound, photographs, graphics, video, messages, tags and/or other materials accessible through the Kidstir Properties (<b>"Content"</b>) that you have provided to and stored in your Third-Party Account (<b>"SNS Content"</b>) so that it is available on and through the Kidstir Properties via your Account. Unless otherwise specified in the Terms, all SNS Content shall be considered to be Your Content (as defined in Section 4.1) for all purposes of the Terms. Depending on the Third-Party Accounts you choose and subject to the privacy settings that you have set in such Third-Party Accounts, personally identifiable information that you post to your Third-Party Accounts may be available on and through your Account on the Kidstir Properties. Please note that if a Third-Party Account or associated service becomes unavailable or Kidstir's access to such Third-Party Account is terminated by the third-party service provider, then SNS Content will no longer be available on and through the Kidstir Properties. You have the ability to disable the connection between your Account and your Third-Party Accounts at any time by accessing the "Settings" section of the Website. PLEASE NOTE THAT YOUR RELATIONSHIP WITH THE THIRD-PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD-PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD-PARTY SERVICE PROVIDERS, AND KIDSTIR DISCLAIMS ANY LIABILITY FOR PERSONALLY IDENTIFIABLE INFORMATION THAT MAY BE PROVIDED TO IT BY SUCH THIRD-PARTY SERVICE PROVIDERS IN VIOLATION OF THE PRIVACY SETTINGS THAT YOU HAVE SET IN SUCH THIRD-PARTY ACCOUNTS. Kidstir makes no effort to review any SNS Content for any purpose, including but not limited to, for accuracy, legality or noninfringement, and Kidstir is not responsible for any SNS Content.</p>
<p><b>3.3 </b><b><span class="underline-text">Registration Data</span>.</b> In registering for the Services, you agree to (1) provide true, accurate, current and complete information about yourself as prompted by the Services' registration form (the <b>"Registration Data"</b>); and (2) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. You represent that you are (1) at least thirteen (13) years old; (2) of legal age to form a binding contract; and (3) not a person barred from using the Kidstir Properties under the laws of the United States, your place of residence or any other applicable jurisdiction. You are responsible for all activities that occur under your Account. You agree that you shall monitor your Account to restrict use by minors, and you will accept full responsibility for any unauthorized use of the Kidstir Properties by minors.   You may not share your Account or password with anyone, and you agree to (1) notify Kidstir immediately of any unauthorized use of your password or any other breach of security; and (2) exit from your Account at the end of each session. If you provide any information that is untrue, inaccurate, not current or incomplete, or Kidstir has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Kidstir has the right to suspend or terminate your Account and refuse any and all current or future use of the Kidstir Properties (or any portion thereof). You agree not to create an Account using a false identity or information, or on behalf of someone other than yourself. You agree that you shall not have more than one Account at any given time. Kidstir reserves the right to remove or reclaim any usernames at any time and for any reason, including but not limited to, claims by a third party that a username violates the third party's rights. You agree not to create an Account or use the Kidstir Properties if you have been previously removed by Kidstir, or if you have been previously banned from any of the Kidstir Properties.</p>
<p><b>3.4 </b><b><span class="underline-text">Necessary Equipment and Software</span>.</b> You must provide all equipment and software necessary to connect to the Kidstir Properties, including but not limited to, a mobile device that is suitable to connect with and use the Kidstir Properties, in cases where the Services offer a mobile component. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Kidstir Properties.</p>
<p><b>4. </b><b>Responsibility for Content.</b></p>
<p><b>4.1 </b><b><span class="underline-text">Types of Content</span>.</b> You acknowledge that all Content, including the Kidstir Properties, is the sole responsibility of the party from whom such Content originated. This means that you, and not Kidstir, are entirely responsible for all Content that you upload, post, e-mail, transmit or otherwise make available (<b>"Make Available"</b>) through the Kidstir Properties (<b>"Your Content"</b>), and other Users of the Kidstir Properties, and not Kidstir, are similarly responsible for all Content they Make Available through the Kidstir Properties (<b>"User Content"</b>).</p>
<p><b>4.2 </b><b><span class="underline-text">No Obligation to Pre-Screen Content</span>. </b> You acknowledge that Kidstir has no obligation to pre-screen Content (including, but not limited to, Your Content and User Content), although Kidstir reserves the right in its sole discretion to pre-screen, refuse or remove any Content. By entering into the Terms, you hereby provide your irrevocable consent to such monitoring. You acknowledge and agree that you have no expectation of privacy concerning the transmission of Your Content, including without limitation chat, text, or voice communications. In the event that Kidstir pre-screens, refuses or removes any Content, you acknowledge that Kidstir will do so for Kidstir's benefit, not yours. Without limiting the foregoing, Kidstir shall have the right to remove any Content that violates the Terms or is otherwise objectionable.</p>
<p><b>4.3 </b><b><span class="underline-text">Storage</span>. </b> Unless expressly agreed to by Kidstir in writing elsewhere, Kidstir has no obligation to store any of Your Content that you Make Available on the Kidstir Properties. Kidstir has no responsibility or liability for the deletion or accuracy of any Content, including Your Content; the failure to store, transmit or receive transmission of Content; or the security, privacy, storage, or transmission of other communications originating with or involving use of the Kidstir Properties. Certain Services may enable you to specify the level at which such Services restrict access to Your Content. You are solely responsible for applying the appropriate level of access to Your Content. If you do not choose, the system may default to its most permissive setting. You agree that Kidstir retains the right to create reasonable limits on Kidstir's use and storage of the Content, including Your Content, such as limits on file size, storage space, processing capacity, and similar limits described in the web pages accompanying the Services and as otherwise determined by Kidstir in its sole discretion.</p>
<p><b>5. </b><b>Ownership.</b></p>
<p><b>5.1 </b><b><span class="underline-text">Kidstir Properties</span>.</b> Except with respect to Your Content and User Content, you agree that Kidstir and its suppliers own all rights, title and interest in the Kidstir Properties. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Website, the Services, or the Kidstir Properties.</p>
<p><b>5.2 </b><b><span class="underline-text">Trademarks</span>.</b> Kidstir and other related graphics, logos, service marks and trade names used on or in connection with the Kidstir Properties or in connection with the Services are the trademarks of Kidstir and may not be used without permission in connection with any third-party products or services. Other trademarks, service marks and trade names that may appear on or in the Kidstir Properties are the property of their respective owners.</p>
<p><b>5.3 </b><b><span class="underline-text">Other Content</span>.</b> Except with respect to Your Content, you agree that you have no right or title in or to any Content that appears on or in the Kidstir Properties.</p>
<p><b>5.4 </b><b><span class="underline-text">Your Content</span>.</b> Kidstir does not claim ownership of Your Content. However, when you as a User post or publish Your Content on or in the Kidstir Properties, you represent that you own and/or have a royalty-free, perpetual, irrevocable, worldwide, non-exclusive right (including any moral rights) and license to use, license, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, derive revenue or other remuneration from, and communicate to the public, perform and display Your Content (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or later developed, for the full term of any worldwide intellectual property right that may exist in Your Content.</p>
<p><b>5.5 </b><b><span class="underline-text">License to Your Content</span>.</b> Subject to any applicable account settings that you select, you grant Kidstir a fully paid, royalty-free, perpetual, irrevocable, worldwide, royalty-free, non-exclusive and fully sublicensable right (including any moral rights) and license to use, license, distribute, reproduce, modify, adapt, publicly perform, publicly display, derive revenue or other remuneration from, and communicate to the public, Your Content (in whole or in part) and/or to incorporate it in other works in any form, media or technology now known or later developed, for the full term of any worldwide intellectual property right, including moral rights, that may exist in Your Content. Please remember that other Users may search for, see, use, modify and reproduce any of Your Content that you submit to any "public" area of the Kidstir Properties, including workspaces. You warrant that the holder of any worldwide intellectual property right, including moral rights, in Your Content, has completely and effectively waived all such rights and validly and irrevocably granted to you the right to grant the license stated above<b>. </b>You agree that you, not Kidstir, are responsible for all of Your Content that you Make Available on or in the Kidstir Properties.</p>
<p><b>5.6 </b><b><span class="underline-text">Username</span>.</b> Notwithstanding anything contained herein to the contrary, by submitting Your Content to any forums, comments or any other area on the Kidstir Properties, you hereby expressly permit Kidstir to identify you by your username (which may be a pseudonym) as the contributor of Your Content in any publication in any form, media or technology now known or later developed in connection with Your Content.</p>
<p><b>5.7 </b><b><span class="underline-text">Your Account</span>.</b> Notwithstanding anything to the contrary herein, you acknowledge and agree that you shall have no ownership or other property interest in your Account, and you further acknowledge and agree that all rights in and to your Account are and shall forever be owned by and inure to the benefit of Kidstir.</p>
<p><b>5.8 </b><b><span class="underline-text">Your Profile</span>. </b> Any Content posted by you in your profile may not contain nudity, violence, sexually explicit, or offensive subject matter. You may not post or submit for print services a photograph of another person without that person's permission.</p>
<p><b>5.9 </b><b><span class="underline-text">Feedback</span>.</b> You agree that submission of any ideas, suggestions, documents, and/or proposals to Kidstir through its suggestion, feedback, wiki, forum or similar pages (<b>"Feedback"</b>) is at your own risk and that Kidstir has no obligations (including without limitation obligations of confidentiality) with respect to such Feedback. You represent and warrant that you have all rights necessary to submit the Feedback. You hereby grant to Kidstir a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights, in connection with the operation and maintenance of the Kidstir Properties.</p>
<p><b>6. </b><b>User Conduct.</b></p>
<p><b>6.1 </b><b><span class="underline-text">Commercial Activities</span>.</b> You agree that you will not, under any circumstances (except to the extent expressly authorized by the Terms):</p>
<p><b>(a) </b>Reproduce, duplicate, copy, sell, trade, resell or exploit for any commercial purpose any portion of the Kidstir Properties (including your Account), or access to or use of the Kidstir Properties;</p>
<p><b>(b) </b>Upload, post, e-mail, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation;</p>
<p><b>(c) </b>Use the Kidstir Properties or any part thereof for any commercial purpose, including, but not limited to communicating or facilitating any commercial advertisement or solicitation;</p>
<p><b>(d) </b>Engage in any chain letters, contests, junk email, pyramid schemes, spamming, surveys or other duplicative or unsolicited messages (commercial or otherwise); or</p>
<p><b>(e) </b>Market any goods or services for any business purposes.</p>
<p><b>6.2 </b><b><span class="underline-text">Unauthorized Use or Access</span>.</b> You agree that you will not, under any circumstances:</p>
<p><b>(a) </b>Interfere or attempt to interfere with the proper functioning of the Kidstir Properties or connect to or use the Kidstir Properties in any way not expressly permitted by the Terms;</p>
<p><b>(b) </b>Systematically retrieve data or other content from our Kidstir Properties to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, spiders, or otherwise;</p>
<p><b>(c) </b>Use, display, mirror or frame the Kidstir Properties, or any individual element within the Kidstir Properties, Kidstir's name, any Kidstir trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Kidstir's express written consent;</p>
<p><b>(d) </b>Use any unauthorized software that accesses, intercepts, "mines" or otherwise collects information from or through the Kidstir Properties or that is in transit from or to the Kidstir Properties, including, but not limited to, any software that reads areas of RAM or streams of network traffic used by the Kidstir Properties;</p>
<p><b>(e) </b>Intercept, examine or otherwise observe any proprietary communications protocol used by a client, a server or the Kidstir Properties, whether through the use of a network analyzer, packet sniffer or other device;</p>
<p><b>(f) </b>Make any automated use of the Kidstir Properties, or take any action that imposes or may impose (in Kidstir's sole discretion) an unreasonable or disproportionately large load on the infrastructure for the Kidstir Properties;</p>
<p><b>(g) </b>Bypass any robot exclusion headers or other measures Kidstir takes to restrict access to the Kidstir Properties, or use any software, technology or device to send content or messages, scrape, spider or crawl the Kidstir Properties, or harvest or manipulate data;</p>
<p><b>(h) </b>Use, facilitate, create, or maintain any unauthorized connection to the Kidstir Properties, including, but not limited to: (i) any connection to any unauthorized server that emulates, or attempts to emulate, any part of the Kidstir Properties; or (ii) any connection using programs, tools or software not expressly approved by Kidstir;</p>
<p><b>(i) </b>Reverse engineer, decompile, disassemble, decipher or otherwise attempt to derive the source code for any underlying software or other intellectual property used to provide the Kidstir Properties, or to obtain any information from the Kidstir Properties;</p>
<p><b>(j) </b>Forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Kidstir Properties;</p>
<p><b>(k) </b>Upload, post, e-mail, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</p>
<p><b>(l) </b>Solicit or attempt to solicit personal information from other Users of the Kidstir Properties;</p>
<p><b>(m) </b>Use the Kidstir Properties to collect, harvest, transmit, distribute, post or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information or credit, debit, calling card or account numbers;</p>
<p><b>(n) </b>Forge any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting, or in any way use the Kidstir Properties to send altered, deceptive or false source-identifying information; or</p>
<p><b>(o) </b>Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including, but not limited to, clear GIFs, 1&#215;1 pixels, web bugs, cookies or other similar devices (sometimes referred to as "spyware," "passive collection mechanisms" or "pcms").</p>
<p><b>6.3 </b><b><span class="underline-text">General</span>.</b> In connection with your use of the Kidstir Properties, you shall not:</p>
<p><b>(a) </b>Make Available any Content that (i) is unlawful, tortious, defamatory, vulgar, obscene, libelous, or racially, ethnically or otherwise objectionable; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or threatening, or promotes violence or actions that are threatening to any other person; or (v) promotes illegal or harmful activities;</p>
<p><b>(b) </b>Harm minors in any way;</p>
<p><b>(c) </b>Impersonate any person or entity, including, but not limited to, Kidstir personnel, or falsely state or otherwise misrepresent your affiliation with a person or entity;</p>
<p><b>(d) </b>Make available any Content that you do not have a right to Make Available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under non-disclosure agreements);</p>
<p><b>(e) </b>Make Available any Content that infringes the rights of any person or entity, including without limitation, any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary or contractual rights;</p>
<p><b>(f) </b>Intentionally or unintentionally violate any applicable local, state, national or international law or regulation, or any order of a court;</p>
<p><b>(g) </b>Register for more than one Account or register for an Account on behalf of an individual other than yourself;</p>
<p><b>(h) </b>Stalk or otherwise harass any other User of our Kidstir Properties; or</p>
<p><b>(i) </b>Advocate, encourage or assist any third party in doing any of the foregoing activities in this section.</p>
<p><b>7. </b><b>Investigations.</b> Kidstir may, but is not obligated to, monitor or review the Kidstir Properties and Content at any time. Without limiting the foregoing, Kidstir shall have the right, in its sole discretion, to remove any of Your Content for any reason (or no reason), including if such Content violates the Terms or any applicable law. Although Kidstir does not generally monitor user activity occurring in connection with the Kidstir Properties or Content, if Kidstir becomes aware of any possible violations by you of any provision of the Terms, Kidstir reserves the right to investigate such violations, and Kidstir may, at its sole discretion, immediately terminate your license to use the Kidstir Properties, or change, alter or remove Your Content, in whole or in part, without prior notice to you.</p>
<p><b>8. </b><b>Interactions with Other Users.</b></p>
<p><b>8.1 </b><b><span class="underline-text">User Responsibility</span>. </b>You are solely responsible for your interactions with other Users of the Services and any other parties with whom you interact through the Services; provided, however, that Kidstir reserves the right, but has no obligation, to intercede in such disputes. You agree that Kidstir will not be responsible for any liability incurred as the result of such interactions.</p>
<p><b>8.2 </b><b><span class="underline-text">Content Provided by Other Users</span>.</b> The Kidstir Properties may contain User Content provided by other Users. Kidstir is not responsible for and does not control User Content. Kidstir has no obligation to review or monitor, and does not approve, endorse or make any representations or warranties with respect to User Content. You use all User Content and interact with other Users at your own risk.</p>
<p><b>9. </b><b>Third-Party Services. </b>The Kidstir Properties may contain links to third-party websites (<b>"Third-Party Websites"</b>) and advertisements for third parties (collectively, <b>"Third-Party Websites &amp; Ads"</b>). When you click on a link to a Third-Party Website or Ad, we will not warn you that you have left the Kidstir Properties and are subject to the terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites are not under the control of Kidstir. Kidstir is not responsible for any Third-Party Websites &amp; Ads. Kidstir provides these Third-Party Websites &amp; Ads only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites &amp; Ads, or their products or services. You use all links in Third-Party Websites &amp; Ads at your own risk. When you leave our Website, our Terms and policies no longer govern. You should review applicable terms and policies, including privacy and data gathering practices, of any Third-Party Websites, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.</p>
<p><b>10. </b><b>Fees and Purchase Terms.</b></p>
<p><b>10.1 </b><b>Payment</b>. To make a payment, you will need to provide Kidstir with the information necessary to process your Order or your Membership, including your shipping address and the billing information requested on the Website. We may use a third-party payment provider (the "<b>Payment Provider</b>") to bill you through a payment account linked to your Account (your "<b>Billing Account</b>"). The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Provider in addition to this Agreement. We are not responsible for error by the Payment Provider. By becoming a Member or placing an Order, you agree to pay us, through the Payment Provider, all applicable charges applicable to your Account and you authorize us, through the Payment Provider, to charge your chosen payment provider (your "<b>Payment Method</b>"). You agree to make payment using that selected Payment Method. We reserve the right to correct any errors or mistakes that it makes even if it has already requested or received payment. You authorize us to charge your Billing Account at our convenience but within thirty (30) days of credit card authorization. You represent that you will not use any Billing Account unless you have all necessary authorization to do so. We assume that because Billing Accounts require a valid credit card, only persons age 18 or over are placing Orders or becoming Members. We shall not be liable in the event your children or others acting with or without your permission use your credit card or other means of payment to make purchases on the Website (and to the extent your minor children make any such purchases, you hereby represent and warrant that they are authorized to do so); however you may report any unauthorized use to us, and we will use reasonable measures within our control to help prevent future unauthorized use of your card.</p>
<p><b>10.2 </b><b>Membership</b>. Membership at Kidstir consists of an initial period, for which there is a one-time charge, followed by recurring period charges as agreed to by you. By choosing a recurring payment plan, you acknowledge that Membership has an initial and recurring payment feature and you accept responsibility for all recurring charges prior to cancellation. WE MAY SUBMIT PERIODIC CHARGES (E.G., WEEKLY OR MONTHLY) WITHOUT FURTHER AUTHORIZATION FROM YOU, UNTIL YOU PROVIDE PRIOR NOTICE (RECEIPT OF WHICH IS CONFIRMED BY US) THAT YOU HAVE TERMINATED THIS AUTHORIZATION OR WISH TO CHANGE YOUR PAYMENT METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE WE REASONABLY COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, PLEASE ACCESS YOUR ACOUNT PAGE ON THE SERVICES. You must promptly notify us if your Payment Method is canceled (e.g., for loss or theft) or if you become aware of a potential breach of security, such as the unauthorized use of your Account.</p>
<p><b>(a) </b><i>Change in Amount Authorized</i>. If the amount to be charged to your Billing Account varies from the amount you preauthorized (other than due to the imposition or change in the amount of state sales taxes), you have the right to receive, and we shall provide, notice of the amount to be charged and the date of the charge before the scheduled date of the transaction. Any agreement you have with your payment provider will govern your use of your Payment Method. You agree that we may accumulate charges incurred and submit them as one or more aggregate charges during or at the end of each billing cycle.</p>
<p><b>(b) </b><i>Auto-Renewal for Membership.</i> Unless you terminate your subscription, which can be done through your Account, your Membership will be automatically extended for successive renewal periods of the same duration as the subscription term originally selected, at the then-current non-promotional rate. To change or terminate any Membership at any time, go to _______________, provided that any termination will not be effective until the end of your then-current term. You won&#8217;t be eligible for a prorated refund of any portion of the subscription fee paid for the then-current subscription period.</p>
<p><b>(c) </b><i>Reaffirmation of Authorization</i>. Your non-termination or continued Membership reaffirms that we are authorized to charge your Payment Method for Membership. Upon renewal of your subscription, if Kidstir does not receive payment from your Payment Provider: (i) you agree to pay all amounts due on your Account upon demand, and/or (ii) you agree that Kidstir may either terminate or suspend your subscription and continue to attempt to charge your Payment Provider until payment is received (upon receipt of payment, your Account will be re-activated and for purposes of automatic renewal, your new membership commitment period will begin as of the day payment was received). This does not waive our right to seek payment directly from you. Your charges may be payable in advance, in arrears, per usage, or as otherwise described when you initially selected to become a Member.</p>
<p><b>(d) </b><i>Free Trials.</i> Any free trial or other promotion that provides Membership must be used within the specified time of the trial. You will be asked for valid credit card information when you sign up for the free trial. We will use the payment information for future Membership fees should you fail to terminate the trial Membership within the timeframe provided by Kidstir. We will start your free trial upon completion of your trial signup. You may cancel your trial Membership without charge at any time within [7] days of placing your order. <strong>If you do not cancel your free trial Membership within </strong>[7]<strong> days of the date you start your trial, your Membership will continue automatically and the monthly fee will be billed to the credit card or other billing source provided by you when you signed up for the trial, on the first day of each successive Membership term. Such billing will occur without further notice to you.</strong> Should you choose to discontinue your Membership for any reason before expiration of the then applicable Membership term or the trial period, you may cancel your Membership and terminate future billing by making the selection on your Account page. <strong>You must cancel your Membership before the end of the trial period in order to avoid being charged a Membership fee.</strong> If you cancel prior to the end of the trial period and are inadvertently charged for a Membership, please contact Kidstir to have the charges reversed.</p>
<p><b>10.3 </b><b><span class="underline-text">Other Promotions</span>.</b> We may run promotional offers from time to time on the Website. The terms of any such promotion will be posted on the Website. Unless otherwise indicated, we may establish and modify, in our sole discretion, the terms of such offer and end such offer at any point.</p>
<p><b>10.4 </b><b><span class="underline-text">Disputes</span>.</b> You must notify us in writing within seven (7) days after receiving your credit card statement, if you dispute any of our charges on that statement or such dispute will be deemed waived. Please use our Contact Us form for any billing disputes.</p>
<p><b>11. </b><b>Indemnification. </b>You agree to indemnify and hold Kidstir, its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (collectively, the <b>"Kidstir Parties"</b>) harmless from any losses, costs, liabilities and expenses (including reasonable attorneys' fees) relating to or arising out of: (a) Your Content; (b) your use of, or inability to use, the Kidstir Properties; (c) your violation of the Terms; (d) your violation of any rights of another party, including any Users; or (e) your violation of any applicable laws, rules or regulations. Kidstir reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Kidstir in asserting any available defenses. You agree that the provisions in this section will survive any termination of your Account, the Terms or your access to the Kidstir Properties.</p>
<p><b>12. </b><b>Disclaimer of Warranties.</b></p>
<p><b>12.1 </b><b><span class="underline-text">As Is</span>.</b> YOU EXPRESSLY UNDERSTAND AND AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE KIDSTIR PROPERTIES AND ANY PRODUCTS AND KITS IS AT YOUR SOLE RISK, AND THE KIDSTIR PROPERTIES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITH ALL FAULTS. THE KIDSTIR PARTIES EXPRESSLY DISCLAIM ALL WARRANTIES, REPRESENTATIONS, AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
<p><b>(a) </b>The KIDSTIR PARTIES MAKE NO WARRANTY, REPRESENTATION OR CONDITION THAT: (1) THE KIDSTIR PROPERTIES OR PRODUCTS WILL MEET YOUR REQUIREMENTS; (2) YOUR USE OF THE KIDSTIR PROPERTIES OR PRODUCTS WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (3) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE KIDSTIR PROPERTIES OR PRODUCTS WILL BE ACCURATE OR RELIABLE; OR (4) ANY ERRORS IN THE KIDSTIR PROPERTIES OR PRODUCTS WILL BE CORRECTED.</p>
<p><b>(b) </b>ANY CONTENT DOWNLOADED FROM OR OTHERWISE ACCESSED THROUGH THE KIDSTIR PROPERTIES OR PRODUCTS IS ACCESSED AT YOUR OWN RISK, AND YOU SHALL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY OR PERSON, INCLUDING, BUT NOT LIMITED TO, YOUR COMPUTER SYSTEM AND ANY DEVICE YOU USE TO ACCESS THE KIDSTIR PROPERTIES, OR ANY OTHER LOSS THAT RESULTS FROM ACCESSING SUCH CONTENT.</p>
<p><b>(c) </b>THE SERVICES MAY BE SUBJECT TO DELAYS, CANCELLATIONS AND OTHER DISRUPTIONS. KIDSTIR MAKES NO WARRANTY, REPRESENTATION OR CONDITION WITH RESPECT TO SERVICES, INCLUDING BUT NOT LIMITED TO, THE QUALITY, EFFECTIVENESS, REPUTATION AND OTHER CHARACTERISTICS OF SERVICES OR PRODUCTS.</p>
<p><b>(d) </b>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM KIDSTIR OR THROUGH THE KIDSTIR PROPERTIES OR PRODUCTS WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
<p><b>(e) </b>From time to time, Kidstir may offer new "beta" features or tools with which its users may experiment. Such features or tools are offered solely for experimental purposes and without any warranty of any kind, and may be modified or discontinued at Kidstir's sole discretion. The provisions of this section apply with full force to such features or tools.</p>
<p><b>12.2 </b><b><span class="underline-text">No Liability for Conduct of Third Parties</span>.</b> YOU ACKNOWLEDGE AND AGREE THAT KIDSTIR PARTIES ARE NOT LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD KIDSTIR PARTIES LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OPERATORS OF EXTERNAL SITES, AND THAT THE RISK OF INJURY FROM SUCH THIRD PARTIES RESTS ENTIRELY WITH YOU. KIDTSIR MAKES NO WARRANTY THAT THE GOODS OR SERVICES PROVIDED BY THIRD PARTIES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. KIDSTIR MAKES NO WARRANTY REGARDING THE QUALITY OF ANY SUCH GOODS OR SERVICES, OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY USER CONTENT OBTAINED THROUGH THE KIDSTIR PROPERTIES.</p>
<p><b>12.3 </b><b><span class="underline-text">No Liability for Conduct of Other Users</span>.</b> YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE KIDSTIR PROPERTIES. YOU UNDERSTAND THAT KIDSTIR DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE KIDSTIR PROPERTIES. KIDSTIR MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE KIDSTIR PROPERTIES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE KIDSTIR PROPERTIES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE KIDSTIR PROPERTIES, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON. YOU ACKNOWLEDGE AND AGREE THAT KIDSTIR DOES NOT CONDUCT BACKGROUND CHECKS ON ANY USER.</p>
<p><b>12.4 </b><b><span class="underline-text">EXCLUSION OF WARRANTIES, ETC</span></b>. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, REPRESENTATIONS OR CONDITIONS, THE LIMITATION OR EXCLUSION OF IMPLIED WARRANTIES, OR LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY MAY LAST, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY IN FULL TO YOU. WHERE LEGISLATION IN A JURISDICTION IMPLIES IN THE TERMS ANY CONDITION OR WARRANTY THAT CANNOT BE EXCLUDED, KIDSTIR'S LIABILITY FOR BREACH THEREOF SHALL BE LIMITED AT KIDSTIR'S OPTION TO ONE OR MORE OF THE FOLLOWING: (1) WHERE THE BREACH OF THE CONDITION OR WARRANTY RELATES TO GOODS, THE REPLACEMENT OR REPAIR OF THE GOODS, THE SUPPLY OF EQUIVALENT GOODS OR PAYMENT OF THE COST OF DOING SO; AND (2) WHERE THE BREACH OF THE CONDITION OR WARRANTY RELATES TO SERVICES, THE SUPPLY OF SERVICES AGAIN, OR THE PAYMENT OF THE COST OF HAVING THEM SUPPLIED AGAIN..</p>
<p><b>13. </b><b>Limitation of Liability.</b></p>
<p><b>13.1 </b><b><span class="underline-text">Disclaimer of Certain Damages</span>.</b> YOU UNDERSTAND AND AGREE THAT IN NO EVENT SHALL THE KIDSTIR PARTIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE KIDSTIR PROPERTIES OR PRODUCTS, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROFITS, WHETHER OR NOT KIDSTIR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THE TERMS, OR FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE KIDSTIR PROPERTIES, ON ANY THEORY OF LIABILITY, RESULTING FROM: (1) THE USE OR INABILITY TO USE THE KIDSTIR PROPERTIES OR PRODUCTS; (2) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED FOR TRANSACTIONS ENTERED INTO THROUGH THE KIDSTIR PROPERTIES; (3) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (4) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE KIDSTIR PROPERTIES; OR (5) ANY OTHER MATTER RELATED TO THE KIDSTIR PROPERTIES, WHETHER BASED ON WARRANTY, COPYRIGHT, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY.</p>
<p><b>13.2 </b><b><span class="underline-text">Cap on Liability</span>.</b> UNDER NO CIRCUMSTANCES WILL THE KIDSTIR PARTIES BE LIABLE TO YOU FOR MORE THAN THE AMOUNT RECEIVED BY KIDSTIR FROM YOU OR PAID BY OFFICE HOURS TO YOU IN THE THREE (3) MONTHS PRIOR TO THE DATE ON WHICH YOU FIRST ASSERT A CLAIM. IF YOU HAVE NOT PAID KIDSTIR ANY AMOUNTS IN SUCH PERIOD, KIDSTIR'S SOLE AND EXCLUSIVE LIABILITY SHALL BE LIMITED TO TEN DOLLARS ($10.00).</p>
<p><b>13.3 </b><b><span class="underline-text">User Content</span>.</b> KIDSTIR PARTIES ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY CONTENT (INCLUDING, BUT NOT LIMITED TO, YOUR CONTENT AND USER CONTENT), USER COMMUNICATIONS OR PERSONALIZATION SETTINGS.</p>
<p><b>13.4 </b><b><span class="underline-text">Basis of the Bargain</span>.</b> THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN KIDSTIR AND YOU.</p>
<p><b>13.5 </b><b><span class="underline-text">EXCLUSION OF DAMAGES</span>.</b> CERTAIN JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>
<p><b>14. </b><b>Procedure for Making Claims of Copyright Infringement.</b> It is Kidstir's policy to terminate membership privileges of any User who repeatedly infringes copyright upon prompt notification to Kidstir by the copyright owner or the copyright owner's legal agent. Without limiting the foregoing, if you believe that your work has been copied and posted on the Kidstir Properties in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on the Kidstir Properties of the material that you claim is infringing; (4) your address, telephone number and e-mail address; (5) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; and (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. Contact information for Kidstir's Copyright Agent for notice of claims of copyright infringement is as follows: Kidstir LLC., 1933 Westridge Terrace, LA, CA 90049, Attn: Copyright Agent.</p>
<p><b>15. </b><b>Term and Termination. </b></p>
<p><b>15.1 </b><b><span class="underline-text">Term</span>.</b> The Terms commence on the date when you accept them (as described in the preamble above) and remain in full force and effect while you use the Kidstir Properties, unless terminated earlier in accordance with the Terms.</p>
<p><b>15.2 </b><b><span class="underline-text">Prior Use</span>. </b> Notwithstanding the foregoing, if you used the Kidstir Properties prior to the date you accepted the Terms, you hereby acknowledge and agree that the Terms commenced on the date you first used the Kidstir Properties (whichever is earlier) and will remain in full force and effect while you use the Kidstir Properties, unless earlier terminated in accordance with the Terms.</p>
<p><b>15.3 </b><b><span class="underline-text">Termination of Services by Kidstir</span>. </b>Kidstir has the right to suspend or terminate any Services provided to you for any reason, including if timely payment cannot be charged to your Payment Provider for any reason, if you have materially breached any provision of the Terms, or if Kidstir is required to do so by law (e.g., where the provision of the Website, the Application, the Software or the Services is, or becomes, unlawful),. You agree that all terminations for cause shall be made in Kidstir's sole discretion and that Kidstir shall not be liable to you or any third party for any termination of your Account. <b></b></p>
<p><b>15.4 </b><b><span class="underline-text">Termination of Services by You</span></b><b>. </b>If you want to terminate the Services provided by Kidstir, you may do so by (a) notifying Kidstir at any time and (<b>b</b>) closing your Account for all of the Services that you use. Please see Section 1.5 above for details on cancelling a Membership.<b></b></p>
<p><b>15.5 </b><b><span class="underline-text">Effect of Termination</span>.</b> Termination of any Service includes removal of access to such Service and barring of further use of the Service. Termination of all Services also includes deletion of your password and all related information, files and Content associated with or inside your Account (or any part thereof), including Your Content. Upon termination of any Service, your right to use such Service will automatically terminate immediately. You understand that any termination of Services may involve deletion of Your Content associated therewith from our live databases. Kidstir will not have any liability whatsoever to you for any suspension or termination, including for deletion of Your Content. All provisions of the Terms which by their nature should survive, shall survive termination of Services, including without limitation, ownership provisions, warranty disclaimers, and limitation of liability.</p>
<p><b>16. </b><b>Remedies.</b></p>
<p><b>16.1 </b><b><span class="underline-text">Violations</span>.</b> If Kidstir becomes aware of any possible violations by you of the Terms, Kidstir reserves the right to investigate such violations. If, as a result of the investigation, Kidstir believes that criminal activity has occurred, Kidstir reserves the right to refer the matter to, and to cooperate with, any and all applicable legal authorities. Kidstir is entitled, except to the extent prohibited by applicable law, to disclose any information or materials on or in the Kidstir Properties, including Your Content, in Kidstir's possession in connection with your use of the Kidstir Properties, to (1) comply with applicable laws, legal process or governmental request; (2) enforce the Terms, (3) respond to any claims that Your Content violates the rights of third parties, (4) respond to your requests for customer service, or (5) protect the rights, property or personal safety of Kidstir, its Users or the public, and all enforcement or other government officials, as Kidstir in its sole discretion believes to be necessary or appropriate.</p>
<p><b>16.2 </b><b><span class="underline-text">Breach</span>.</b> In the event that Kidstir determines, in its sole discretion, that you have breached any portion of the Terms, or have otherwise demonstrated conduct inappropriate for the Kidstir Properties, Kidstir reserves the right to:</p>
<p><b>(a) </b>Warn you via e-mail (to any e-mail address you have provided to Kidstir) that you have violated the Terms;</p>
<p><b>(b) </b>Delete any of Your Content provided by you or your agent(s) to the Kidstir Properties;</p>
<p><b>(c) </b>Discontinue your registration(s) with the any of the Kidstir Properties, including any Services or any Kidstir community;</p>
<p><b>(d) </b>Discontinue your Membership or subscription to any Services;</p>
<p><b>(e) </b>Notify and/or send Content to and/or fully cooperate with the proper law enforcement authorities for further action; and/or</p>
<p><b>(f) </b>Pursue any other action which Kidstir deems to be appropriate.</p>
<p><b>16.3 </b><b><span class="underline-text">No Subsequent Registration</span>.</b> If your registration(s) with or ability to access the Kidstir Properties, or any other Kidstir community is discontinued by Kidstir due to your violation of any portion of the Terms or for conduct otherwise inappropriate for the community, then you agree that you shall not attempt to re-register with or access the Kidstir Properties or any Kidstir community through use of a different member name or otherwise, and you acknowledge that you will not be entitled to receive a refund for fees related to those Kidstir Properties to which your access has been terminated. In the event that you violate the immediately preceding sentence, Kidstir reserves the right, in its sole discretion, to immediately take any or all of the actions set forth herein without any notice or warning to you.</p>
<p><b>17. </b><b>International Users. </b>The Kidstir Properties can be accessed from countries around the world and may contain references to Services and Content that are not available in your country. These references do not imply that Kidstir intends to announce such Services or Content in your country. The Kidstir Properties are controlled and offered by Kidstir from its facilities in the United States of America. Kidstir makes no representations that the Kidstir Properties are appropriate or available for use in other locations. Those who access or use the Kidstir Properties from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>
<p><b>18. </b><b>General Provisions.</b></p>
<p><b>18.1 </b><b><span class="underline-text">Electronic Communications</span>.</b> The communications between you and Kidstir use electronic means, whether you visit the Kidstir Properties or send Kidstir e-mails, or whether Kidstir posts notices on the Kidstir Properties or communicates with you via e-mail. For contractual purposes, you (1) consent to receive communications from Kidstir in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Kidstir provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. The foregoing does not affect your statutory rights.</p>
<p><b>18.2 </b><b><span class="underline-text">Release</span>.</b> You hereby release Kidstir Parties and their successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injuries, death, and property damage, that is either directly or indirectly related to or arises from your use of the Kidstir Properties, including but not limited to, any interactions with or conduct of other Users or third-party websites of any kind arising in connection with or as a result of the Terms or your use of the Kidstir Properties. If you are a California resident, you hereby waive California Civil Code Section 1542, which states, "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."</p>
<p><b>18.3 </b><b><span class="underline-text">Assignment</span>.</b> The Terms, and your rights and obligations hereunder, may not be assigned, subcontracted, delegated or otherwise transferred by you without Kidstir's prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.</p>
<p><b>18.4 </b><b><span class="underline-text">Force Majeure</span>.</b> Kidstir shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargos, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials.</p>
<p><b>18.5 </b><b><span class="underline-text">Compliance</span>.</b> If you believe that Kidstir has not adhered to the Terms, please contact Kidstir by using our Contact Us form. We will do our best to address your concerns. If you feel that your complaint has not been addressed completely, we invite you to let us know for further investigation.</p>
<p><b>18.6 </b><b><span class="underline-text">Limitations Period</span>. </b>YOU AND KIDSTIR AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE TERMS, THE KIDSTIR PROPERTIES OR THE CONTENT MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
<p><b>18.7 </b><b><span class="underline-text">Dispute Resolution</span>.</b></p>
<p><b>(a) </b>Any claim or dispute (excluding claims for injunctive or other equitable relief as set forth below) in connection with the Terms where the total amount of the award sought is less than Five Thousand U.S. Dollars (US $5,000.00) may be resolved in a cost effective manner through binding non-appearance-based arbitration, at the option of the party seeking relief. Such arbitration shall be initiated through an established alternative dispute resolution provider (<b>"ADR Provider"</b>) that offers arbitration as set forth in this section and under the rules of such ADR Provider, except to the extent such rules are in conflict with the Terms. The party demanding arbitration will propose an ADR Provider and the other party shall not unreasonably withhold consent to use such ADR Provider. The ADR Provider and the parties must comply with the following rules: (1) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (2) all arbitration proceedings shall be held in English; (3) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed to by the parties; and (4) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Each party shall bear its own costs (including attorney fees) and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the ADR Provider. Notwithstanding the foregoing, Kidstir may seek injunctive or other equitable relief to protect its intellectual property rights in any court of competent jurisdiction. Please note that the laws of the jurisdiction where you are located may be different from California law, including the laws governing what can legally be sold, bought, exported, offered or imported. You shall always comply with all the international and domestic laws, ordinances, regulations and statutes that are applicable to your use of the Kidstir Properties.</p>
<p><b>(b) </b>Any other dispute (including whether the claims asserted are arbitrable) shall be referred to and finally determined by binding and confidential arbitration. Arbitration shall be subject to the Federal Arbitration Act and not any state arbitration law. The arbitration shall be conducted before one commercial arbitrator with substantial experience in resolving commercial contract disputes from the American Arbitration Association (<b>"AAA"</b>). As modified by the Terms, and unless otherwise agreed upon by the parties in writing, the arbitration will be governed by the AAA's Commercial Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer Related Disputes (collectively <b>"Rules and Procedures"</b>).</p>
<p><b>(c) </b>You are thus GIVING UP YOUR RIGHT TO GO TO COURT to assert or defend your rights EXCEPT for matters that may be taken to small claims court. Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury. You are entitled to a <span class="underline-text">FAIR HEARING,</span> BUT the arbitration procedures are <span class="underline-text">SIMPLER AND MORE LIMITED</span> THAN RULES APPLICABLE IN COURT. Arbitrator decisions are as enforceable as any court order and are subject to <span class="underline-text">VERY LIMITED REVIEW</span> BY A COURT.</p>
<p><b>(d) </b>You and Kidstir must abide by the following rules: (i) ANY CLAIMS BROUGHT BY YOU OR KIDSTIR MUST BE BROUGHT IN THE PARTIES' INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING; (ii) THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS, MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND MAY NOT AWARD CLASS-WIDE RELIEF; (iii) in the event that you are able to demonstrate that the costs of arbitration will be prohibitive as compared to costs of litigation, Kidstir will pay as much of your filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive as compared to the cost of litigation; (iv) Kidstir also reserves the right in its sole and exclusive discretion to assume responsibility for all of the costs of the arbitration; (v) the arbitrator shall honor claims of privilege and privacy recognized at law; (vi) the arbitration shall be confidential, and neither you nor we may disclose the existence, content or results of any arbitration, except as may be required by law or for the purposes of enforcement of the arbitration award; (vii) the arbitrator may award any individual relief or individual remedies that are permitted by applicable law; and (viii) each side pays its own attorneys' fees and expenses unless there is a statutory provision that requires the prevailing party to be paid its fees and litigation expenses, and then in such instance, the fees and costs awarded shall be determined by applicable law.</p>
<p><b>(e) </b>The arbitral proceedings, and all pleadings and written evidence will be in the English language. Any written evidence originally in a language other than English will be submitted in English translation accompanied by the original or true copy thereof. The English language version will control. The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator will not have authority to award damages in excess of the amount, or other than the types, allowed by Section 13 of the Terms. Judgment on the award of the arbitrator may be entered by any court of competent jurisdiction. The arbitrator also shall be authorized to grant any temporary, preliminary or permanent equitable remedy or relief it deems just and equitable and within the scope of the Terms, including, without limitation, an injunction or order for specific performance. The arbitration award shall be final and binding upon the parties without appeal or review except as permitted by California law or United States federal law.</p>
<p>Notwithstanding the foregoing, either you or Kidstir may bring an individual action in small claims court. Further, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party's patent, copyright, trademark, or trade secret shall not be subject to this arbitration agreement. Such claims shall be exclusively brought in the state or federal courts located in Los Angeles, California. Additionally, notwithstanding this agreement to arbitrate, either party may seek emergency equitable relief before the state or federal courts located in Los Angeles, California, in order to maintain the status quo pending arbitration, and hereby agree to submit to the exclusive personal jurisdiction of the courts located within Los Angeles, California for such purpose. A request for interim measures shall not be deemed a waiver of the right to arbitrate.</p>
<p><b>(f) </b>With the exception of (d)(i) and (ii) above (prohibiting arbitration on a class or collective basis), if any part of this arbitration provision is deemed to be invalid, unenforceable, or illegal, or otherwise conflicts with the Rules and Procedures, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting provision were not contained herein. If, however, either (d)(i) or (ii) is found to be invalid, unenforceable or illegal, then the entirety of this arbitration provision shall be null and void, and neither you nor Kidstir shall be entitled to arbitration. If for any reason, a claim proceeds in court rather than in arbitration, the dispute shall be exclusively brought in state or federal court in Los Angeles, California. By using the Kidstir Properties in any manner, you agree to the above arbitration provision.</p>
<p>For more information on AAA, its Rules and Procedures, and how to file an arbitration claim, you may call AAA at 800-778-7879 or visit the AAA website at http://www.adr.org.</p>
<p><b>18.8 </b><b><span class="underline-text">Governing Law</span>.</b> The Terms and any action related thereto will be governed and interpreted by and under the laws of the State of California, consistent with the Federal Arbitration Act, without giving effect to any principles that provide for the application of the law of another jurisdiction. The United Nations Convention on Contracts for the International Sale of Goods does not apply to these Terms.</p>
<p><b>18.9 </b><b><span class="underline-text">Choice of Language</span>.</b> It is the express wish of the parties that the Terms and all related documents have been drawn up in English. C'est law volone expresse des parties que la presente convention ainsi que les documents qui s'y rattacent soient rediges en anglais.</p>
<p><b>18.10 </b><b><span class="underline-text">Notice</span>.</b> Where Kidstir requires that you provide an e-mail address, you are responsible for providing Kidstir with your most current e-mail address. In the event that the last e-mail address you provided to Kidstir is not valid, or for any reason is not capable of delivering to you any notices required/ permitted by the Terms, Kidstir's dispatch of the e-mail containing such notice will nonetheless constitute effective notice. You may give notice to Kidstir at the through our Contact Us form. Such notice shall be deemed given when received by Kidstir by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.</p>
<p><b>18.11 </b><b><span class="underline-text">Waiver</span>.</b> Any waiver or failure to enforce any provision of the Terms on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</p>
<p><b>18.12 </b><b><span class="underline-text">Severability</span>.</b> If any provision of the Terms is, for any reason, held to be invalid or unenforceable, the other provisions of the Terms will remain enforceable, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.</p>
<p><b>18.13 </b><b><span class="underline-text">Export Control</span>.</b> You may not use, export, import, or transfer the Kidstir Properties except as authorized by U.S. law, the laws of the jurisdiction in which you obtained the Kidstir Properties, and any other applicable laws. In particular, but without limitation, the Kidstir Properties may not be exported or re-exported (a) into any United States embargoed countries, or (b) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce's Denied Person's List or Entity List. By using the Kidstir Properties, you represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also will not use the Kidstir Properties for any purpose prohibited by U.S. law, including the development, design, manufacture or production of missiles, nuclear, chemical or biological weapons. You acknowledge and agree that products, services or technology provided by Kidstir are subject to the export control laws and regulations of the United States. You shall comply with these laws and regulations and shall not, without prior U.S. government authorization, export, re-export, or transfer Kidstir products, services or technology, either directly or indirectly, to any country in violation of such laws and regulations.</p>
<p><b>18.14 </b><b><span class="underline-text">Entire Agreement</span>.</b> The Terms are the final, complete and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</p>
<p><b>19. </b><b>International Provisions.</b> The following provisions shall apply only if you are located in the countries listed below.</p>
<p><b>19.1 </b><b><span class="underline-text">United Kingdom</span>.</b> A third party who is not a party to the Terms has no right under the Contracts (Rights of Third Parties) Act 1999 to enforce any provision of the Terms, but this does not affect any right or remedy of such third party which exists or is available apart from that Act.</p>
<p><b>19.2 </b><b><span class="underline-text">Germany</span>.</b> Notwithstanding anything to the contrary in Section 13, Kidstir is also not liable for acts of simple negligence (unless they cause injuries to or death of any person), except when they are caused by a breach of any substantial contractual obligations (vertragswesentliche Pflichten).</p>

</section><!-- /.entry -->
	










	</div><!-- End of FAQ -->





</div><!-- End of main container -->



<?php include('footer.php') ?>
